spring:
  mvc:
    view:
      prefix:
      suffix: .html

  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/dauweb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql ? ??
logging.level:
  org.hibernate.SQL: trace # ??? ??? sql ??
